spring:
  application:
    name: notes-app
  data:
    mongodb:
      database: notes_db
      uri: mongodb://localhost:27017/notes_db

server:
  shutdown: graceful
  port: 8080

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true